Remove Moo dependency from Duo::API::Iterator
duosecurity/duo_api_perl pull request #6
Opened 2019-01-18 22:33 UTC by tfpoage

Only applies to 6cf797ae8c21d27026a4e703ff9c17e4568eabd2
(I'm still pretty new to git[hub] fork/merge/...)

A platform we run does not natively support Moo. To avoid having to install and maintain some ~2000 lines of dependent code for Moo, the dependency was removed and replaced with new().

Passes make test.

2019-01-28 20:50 UTC, mbish requested changes
Other than the comment I left this looks good to me. It removes a somewhat large dependency which may limit usage.

2019-01-28 20:50 UTC, mbish commented on lib/Duo/API/Iterator.pm
> +        unless ref($params{$g}) eq 'CODE';
Unless there's a compelling reason I'd rather leave this as Scalar::Util since this will reject blessed subroutines.

2019-01-28 21:14 UTC, tfpoage commented on lib/Duo/API/Iterator.pm
> +        unless ref($params{$g}) eq 'CODE';
I'm OK with re-adding Scalar::Util. I hadn't thought of blessed subroutines.

2019-01-29 21:53 UTC, tfpoage commented on lib/Duo/API/Iterator.pm
> +        unless ref($params{$g}) eq 'CODE';
Re-added Scalar::Util. Tests pass.

2019-01-30 19:44 UTC, mbish approved these changes

2019-01-30 19:47 UTC, merged